name: Java CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Name of version (ie 5.5.0)'
        required: true
jobs:    
  Build_Release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up PATH
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Gradle
      run: ./gradlew deploy
    - name: Upload built jar file
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/${{ github.event.repository.name }}.jar
    – name: Setup release information
      run: |
          version=`sed '2q;d' app_versions.gradle | cut -d "=" -f2 | xargs`
          export VERSION=$version
          echo "::set-env name=VERSION::$VERSION"
    - name: Create a Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release v${{ env.VERSION }}
        tag_name: v${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ env.VERSION }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/${{ github.event.repository.name }}.jar
        asset_name: ${{ github.event.repository.name }}
        asset_content_type: application/java-archive
    
